[package]
name = "nightcycle/instance-pool"
description = "A package!"
version = "1.0.0"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
Signal = "nightcycle/signal@^1.0.2"
Maid = "nightcycle/maid@^1.0.4"